version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile-php  # Use Dockerfile-php for PHP service
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: Thesnake7!
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
